version: '3.9'
services:
    api:
        build:
            target: prod
        restart: always
        volumes:
            - ./:/srv/
            - /srv/node_modules
        ports:
            - 5000:5000
        env_file:
            - ./src/config/prod/.env.prod
