#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx commitlint --edit $1 ||
(
  echo
  echo '🚩 It seems that the format of the commit does not follow the conventional commit convention. Check that your commit message is correct and try again.';
  echo
  false;
)